# Generated by Django 5.0.1 on 2024-02-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phno',
            new_name='phnumber',
        ),
    ]
